---
title: "Reproducing Book 1"
author: "Nikolaus Umlauf"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
bibliography: gamlss2.bib
nocite: |
  @gamlss2:Rigby+Stasinopoulos:2005
vignette: >
  %\VignetteIndexEntry{First Steps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{gamlss2}
  %\VignetteKeywords{distributional regression, first steps}
  %\VignettePackage{gamlss2}
---

```{r preliminaries, echo=FALSE, message=FALSE, results="hide"}
library("gamlss")
library("gamlss2")
library("survival")
```

## Chapter 1: Why GAMLSS

### Gaussian Model

```{r}
## Load the Munich rent data.
data("rent", package = "gamlss.data")

## Estimate models.
r0 <- gamlss(R ~ Fl + A + H + loc, family = NO, data = rent, trace = FALSE)
r1 <- gamlss2(R ~ Fl + A + H + loc, family = NO, data = rent, trace = FALSE)
l1 <- lm(R ~ Fl + A + H + loc, data = rent)

## Compare
coef(r0)
coef(r1)
coef(r1, model = "mu")
coef(r1, what = "mu")
coef(l1)

head(fitted(r0))
head(fitted(r1))
head(fitted(r1, type = "parameter"))
fitted(r1, model = "sigma")[1]
fitted(r1, what = "sigma")[1]
fitted(r1, what = "sigma", type = "parameter")[1]

summary(r0)
summary(r1)

Rsq(r0)
Rsq(r1)

## New Rsq() function accepts multiple objects.
Rsq(r0, r1)

## Plot residuals.
plot(r0)
plot(r1)
plot(r1, which = "resid")
plot(r1, which = "wp-resid")
plot(r1, which = "qq-resid")
plot(r1, which = "hist-resid")
plot(r1, which = "scatter-resid")
```

### Gamma Model

```{r}
r3 <-  gamlss(R ~ Fl + A + H + loc, family = GA, data = rent)
r4 <-  gamlss2(R ~ Fl + A + H + loc, family = GA, data = rent)
coef(r3)
coef(r4)
coef(r4, model = "mu")
coef(r4, model = "sigma")
coef(r4, what = "sigma")
deviance(r3)
deviance(r4)

## GLM
l2 <- glm(R ~ Fl + A + H + loc, family = Gamma(link = "log"), data = rent)
coef(l2)
summary(l2)$dispersion
deviance(l2)

## Compare log-likelihoods.
logLik(r3)
logLik(r4)
logLik(l2)

summary(r3)
summary(r4)
```

### Inverse Gamma Models

```{r}
r5 <-  gamlss(R ~ Fl + A + H + loc, family = IG, data = rent)
r6 <-  gamlss2(R ~ Fl + A + H + loc, family = IG, data = rent)

## New GAIC function.
GAIC(r5)
GAIC(r6)
GAIC(r5, r6)
GAIC(r5, r6, k = 0)

## New methods.
AIC(r6)
BIC(r6)
AIC(r6, r4)
BIC(r6, r4)
```

### Using Splines

```{r}
r7 <-  gamlss(R ~ pb(Fl) + pb(A) + H + loc, family = GA, data = rent)
r8 <-  gamlss2(R ~ s(Fl) + s(A) + H + loc, family = GA, data = rent)
r9 <-  gamlss2(R ~ Fl + A + s(Fl) + s(A) + H + loc, family = GA, data = rent)
r10 <-  gamlss2(R ~ pb2(Fl) + pb2(A) + H + loc, family = GA, data = rent)

## Compare.
GAIC(r7, r8, r9, r10)

## Plot effects.
term.plot(r7, pages = 1, ask = FALSE)
plot(r8, pages = 1)
plot(r9, pages = 1)
plot(r10, pages = 1)
```

### Mu and Sigma Models

```{r}
m1 <-  gamlss(R ~ pb(Fl) + pb(A) + H + loc,
  sigma.fo = ~ pb(Fl) + pb(A) + H + loc, 
  family = GA, data = rent)

m2 <-  gamlss(R ~ pb(Fl) + pb(A) + H + loc,
  sigma.fo = ~ pb(Fl) + pb(A) + H + loc, 
  family = IG, data = rent)

## Use of sigma.formula.
b1 <-  gamlss2(R ~ s(Fl) + s(A) + H + loc,
  sigma.formula = ~ s(Fl) + s(A) + H + loc, 
  family = GA, data = rent)

## New using Formula().
f <- R  ~ s(Fl) + s(A) + H + loc | s(Fl) + s(A) + H + loc

b2 <-  gamlss2(f, family = IG, data = rent)

## Compare.
GAIC(m1, m2, b1, b2)

## Plot.
term.plot(m1, pages = 1, what = "sigma", ask = FALSE)
plot(b1, pages = 1)

## More complex models.
m3 <-  gamlss(R ~ pb(Fl) + pb(A) + H + loc,
  sigma.fo = ~ pb(Fl) + pb(A) + H + loc,
  nu.fo = ~ 1, family = BCCGo, data = rent)

m4 <-  gamlss(R ~ pb(Fl) + pb(A) + H + loc,
  sigma.fo = ~ pb(Fl) + pb(A) + H + loc,
  nu.fo = ~ pb(Fl) + pb(A) + H + loc,
  family = BCCGo, data = rent)

f <- R  ~ s(Fl) + s(A) + H + loc | s(Fl) + s(A) + H + loc

b3 <- gamlss2(f, data = rent, family = BCCGo)

f <- R  ~ s(Fl) + s(A) + H + loc |
  s(Fl) + s(A) + H + loc |
  s(Fl) + s(A) + H + loc

b4 <- gamlss2(f, data = rent, family = BCCGo)

GAIC(m1, m2, m3, m4, b1, b2, b3, b4)

## Plot estimated effects.
plot(b4, model = "mu")
plot(b4, model = "sigma")
plot(b4, model = "nu")

## Plot quantile residuals.
plot(b4, which = "resid")
```

## Chapter 2: gamlss Packages

```{r}
data("film90", package = "gamlss.data")

## Plot the data
plot(lborev1 ~ lboopen, data = film90,
  col = as.integer(film90$dist),
  xlab = "log opening revenue",
  ylab = "log extra revenue")

## Formula.
f <- lborev1 ~ lboopen + I(lboopen^2) + I(lboopen^3)

## Models.
m0 <- gamlss(f, data = film90, family = NO)
b0 <- gamlss2(f, data = film90, family = NO)
l0 <- lm(f, data = film90)

## Plot fitted values.
plot(lborev1 ~ lboopen, col = "lightgray", data = film90)
i <- order(film90$lboopen)
fm0 <- fitted(m0)
fb0 <- fitted(b0, model = "mu")
lines(fm0[i] ~ film90$lboopen[i], col = 2, lwd = 4)
lines(fb0[i] ~ film90$lboopen[i], col = 4, lwd = 2)
```

### Using vcov()

```{r}
## Variance-covariance matrix.
print(vcov(m0), digits = 3)
print(vcov(b0), digits = 3)
print(vcov(l0), digits = 3)

## Using poly()
m1 <- gamlss(lborev1 ~ poly(lboopen, 3), data = film90, family = NO)
b1 <- gamlss2(lborev1 ~ poly(lboopen, 3), data = film90, family = NO)

## Plot correlation matrices.
library("corrplot")

col <- colorRampPalette(c("black", "grey"))

par(mfrow = c(1, 2))

corrplot(vcov(m0, type = "cor"), col = col(2),
  outline = TRUE, tl.col = "black", addCoef.col = "white")

corrplot(vcov(b0, type = "cor"), col = col(2),
  outline = TRUE, tl.col = "black", addCoef.col = "white")
```

### Splines

```{r}
## Using splines.
m2 <- gamlss(lborev1 ~ pb(lboopen), data = film90, family = NO)
summary(m2)

b2 <- gamlss2(lborev1 ~ s(lboopen, k = 20), data = film90, family = NO)
summary(b2)

## Compare.
GAIC(m2, b2)

## Plot.
par(mfrow = c(1, 1))
plot(lborev1 ~ lboopen, col = "lightgray", data = film90)
i <- order(film90$lboopen)
fm2 <- fitted(m2)
fb2 <- fitted(b2, model = "mu")
lines(fm2[i] ~ film90$lboopen[i], col = 2, lwd = 4)
lines(fb2[i] ~ film90$lboopen[i], col = 4, lwd = 2)
```

### Neural Networks

```{r}
library("gamlss.add")

set.seed(123)
m1 <- gamlss(lborev1 ~ nn(~lboopen, size = 20, decay = 0.1),
  data = film90, family = NO)

set.seed(123)
b1 <- gamlss2(lborev1 ~ n(~lboopen, size = 20, decay = 0.1),
  data = film90, family = NO)

## Plot fitted values.
plot(lborev1 ~ lboopen, col = "lightgray", data = film90)
i <- order(film90$lboopen)
fm1 <- fitted(m1)
fb1 <- fitted(b1, model = "mu")
lines(fm1[i] ~ film90$lboopen[i], col = 2, lwd = 4)
lines(fb1[i] ~ film90$lboopen[i], col = 4, lwd = 2)
```

### BCCG & BCPE

```{r}
m2 <- gamlss(lborev1 ~ pb(lboopen), sigma.formula = ~pb(lboopen),
  nu.formula = ~pb(lboopen), data = film90, family = BCCG)

m3 <- gamlss(lborev1 ~ pb(lboopen), sigma.formula = ~pb(lboopen),
  nu.formula = ~pb(lboopen), tau.formula = ~pb(lboopen),
  data = film90, start.from = m2, family = BCPE)

f <- lborev1 ~ pb2(lboopen)|pb2(lboopen)|pb2(lboopen)|pb2(lboopen)

b2 <- gamlss2(f, data = film90, family = BCCG, maxit = c(100, 1))

b3 <- gamlss2(f, data = film90, family = BCPE, maxit = c(100, 1))

## Compare.
GAIC(m2, m3, b2, b3)

## Fitted values.
fittedPlot(m2, m3, x = film90$lboopen, line.type = TRUE)

## Similar with gamlss2.
plot(c(b2, b3))

## Quantiles.
centiles(m3,  xvar = film90$lboopen,
  cent = c(3, 10, 25, 50, 75, 90, 97),
  ylab = "lborev1", xlab = "lboopen")

## Using gamlss2.
quantile(b3, plot = TRUE, variable = TRUE)
```

## Chapter 3: Algorithms

### Species Example using PIG

```{r}
data("species", package = "gamlss.data")

m1 <- gamlss(fish ~ log(lake), sigma.fo =~ log(lake),
  family = PIG, data = species)

m2 <- gamlss(fish ~ log(lake), sigma.fo =~ log(lake),
  family = PIG, data = species, method = CG(), n.cyc = 100)

m3 <- gamlss(fish ~ log(lake), sigma.fo =~ log(lake),
  family = PIG, data = species, method = mixed(1, 100))

f <- fish ~ log(lake) | log(lake)
b1 <- gamlss2(f, data = species, family = PIG)

f <- fish ~ s(sqrt(lake)) | s(sqrt(lake))
b2 <- gamlss2(f, data = species, family = PIG)

GAIC(m1, m2, m3, b1, b2)
```

### Oil Price Example

```{r}
data("oil", package = "gamlss.data")

m1 <- gamlss(OILPRICE ~ pb(respLAG) + pb(HO1_log),
  sigma.formula =~ pb(respLAG) + pb(HO1_log),
  nu.formula =~ pb(respLAG) + pb(HO1_log),
  tau.formula =~ pb(respLAG) + pb(HO1_log),
  family = SHASHo, data = oil, method = mixed(10, 10),
  gd.tol = Inf)

f <- OILPRICE ~ s(respLAG,k=20) + s(HO1_log,k=20) |
  s(respLAG,k=20) + s(HO1_log,k=20) |
  s(respLAG,k=20) + s(HO1_log,k=20) |
  s(respLAG,k=20) + s(HO1_log,k=20)

## Increase number of iterations, start CG algorithm at iteration 10
## of the outer backfitting loop.
b1 <- gamlss2(f, data = oil, family = SHASHo, maxit = c(400, 1), CG = 10)
  
GAIC(m1, b1)
```

